### ISSUE TITLE
Dlls are incompatible with dontet standard

### ISSUE THREAD

**Issue by ambarkhan** [zerodhatech/dotnetkiteconnect#22]

**Comment by ajinasokan** [comment]
We've decided to start the port to .Net standard. I will start the work as early as next week.

**Comment by ajinasokan** [comment]
This issue is being tracked in #25

**Comment by nichil72** [comment]
Hi Buddy,

I am facing a problem while building the application. Please help to do this.
<img width="960" alt="Zerodha_issue" src="https://user-images.githubusercontent.com/78985000/107824404-754eda00-6da7-11eb-9f35-5e39632e946b.png">

**Comment by ajinasokan** [comment]
@nichil72 It seems your Visual Studio/.Net versions are not compatible. [Here](https://github.com/zerodha/dotnetkiteconnect/issues/25#issuecomment-659143382) is the compatible versions. Try upgrading your environment to that. Or if you just need to use the lib then you can directly install it from NuGet instead of manually building it from the source code.

If the problem persists even after that please open a new issue as this one is unrelated.
