### ISSUE TITLE
.net core warning and lack of async

### ISSUE THREAD

**Issue by pavan2sunny** [zerodhatech/dotnetkiteconnect#7]
does't support .net core 
no async functionality

**Comment by ajinasokan** [comment]
Both were conscious decisions. When we started the development of this client library, all the users were using .net standard and .net core was in the early stages of development. 

We don't have any plans to port it to .net core at the moment. Because it will be difficult for the users to migrate their projects. But it will be easy to port because the library is using only the built-in .net framework features.

Async functionality seems to be a feasible addition. For now you can call functions inside a Task like this:

```csharp
Task.Run(() => GetOrders());
```
