### ISSUE TITLE
Static Class Mapping

### ISSUE THREAD

**Issue by sarthak-k** [zerodhatech/dotnetkiteconnect#8]
Hi,

I was just wondering the  reason behind not having static class mapping over dynamic responses, which is far more error prone than classes. Also, the library can have API links as constant pushed to somewhere in other class and utilized RestSharp like libraries for making the calls...

**Comment by ajinasokan** [comment]
@sarthak-k Can you explain what you meant by "static class mapping"?

Using classes as enums for API links will be a cleaner way to do it. We will consider it for the next release. 

Also, when we started this project the idea was to keep it as easy as possible to port to other platforms like .Net core, Xamarin etc. So we didn't use any external dependencies in this project. Everything including the WebSockets uses the classes from .Net framework.

**Comment by sarthak-k** [comment]
Static class mapping is nothing but POCO objects for JSON Mapping. The problem with current implementation is returning dynamic<string, object> I believe, it does not make sense to have a dynamic object and make programs error prone unecessarily.

Using static class for mapping API endpoints reduces the burden of refactoring each time there is change on the Zerodha end. As far as I understand, any library which targets .NET Standard 2.0 can be utilized and will work across all the platforms. Let me know if I can be of any help.

**Comment by ajinasokan** [comment]
I believe we are already doing it in this project. Take a look at [Structures.cs](https://github.com/zerodhatech/dotnetkiteconnect/blob/master/KiteConnect/Structures.cs).

We do not use any external library for the serialization. Instead, the parsed JSON is loaded into the corresponding POCO field by field. So even if there is an API change from the backend, the library remains almost the same. 

Til now, the only time users had to refactor was after KiteConnect 3.0 release, which had major breaking changes and bunch of feature additions. Because of that, we had given ~6 months to users to migrate to this new API. We had also sent reminder emails regarding the same.

Also, we targeted .Net 4.5 instead of previous versions because of multiple reasons. First, previous versions don't have built in WebSocket support. And the one shipped with framework is standard compliant, stable and light compared to external libraries. Second, new versions of Windows don't ship with .Net 2.0 and 3.5 where as 4.5 or above is built in. And since these APIs are dealing with serious data, we encourage our users to be in the latest versions because of the improvements in security and stability they offer.

**Comment by sarthak-k** [comment]
.NET 4.5 and .NET Standard are two different things. It not necessarily required that any application written for .NET 4.5 will work across all the platforms, while any application written over .NET Standard, specifically 2.0 ensures it to run across the .NET ecosystem. With .NET Standard 2.0 implementation you will ensure that user is on the lastest platform both in .NET and .NET Core.

Also, placing an order or modifying an order is still using a dynamic object for returning any data from the API. Also, at the same time, the API can be written in [Fluent](https://github.com/Azure/azure-sdk-for-net/tree/Fluent) fashion (which is much robust and enforce users to use correctly as per the guidelines and required business requirements) and can utilize many helpful libraries for maintaining validation states like FluentValidator, Mapper and etc.

**Comment by ajinasokan** [comment]
I was planning to write a port for .Net core. But like you said .Net Standard 2.0 will be a better target since it can work with both .Net framework and .Net core. 

Also, I will check out the "Flutent" system for the API. Will consider both of them for the next major release.
